# Generated by Django 5.0 on 2023-12-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('player_age', models.IntegerField()),
                ('team_name', models.CharField(max_length=20)),
                ('player_position', models.CharField(max_length=20)),
                ('player_jersey_no', models.IntegerField()),
            ],
        ),
    ]
